# Generated by Django 5.2.1 on 2025-06-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='influencers/')),
                ('voiceid', models.CharField(blank=True, help_text='ElevenLabs Voice ID', max_length=100, null=True)),
                ('feature_model_id', models.CharField(blank=True, help_text='Apply Feature OpenAI Model ID', max_length=100, null=True)),
                ('feature_system_prompt', models.TextField(blank=True, help_text='System Prompt', null=True)),
                ('speech_model_id', models.CharField(blank=True, help_text='Reflect Speech OpenAI Model ID', max_length=100, null=True)),
                ('speech_system_prompt', models.TextField(blank=True, help_text='Reflect Speech System Prompt', null=True)),
                ('created_mode', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=10)),
            ],
        ),
    ]
