# Generated by Django 5.2.1 on 2025-05-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_chat_received', models.IntegerField(default=0)),
                ('thumbs_up', models.IntegerField(default=0)),
                ('price_per_chat', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='influencers/')),
            ],
        ),
    ]
