# Generated by Django 5.2.1 on 2025-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='voiceid',
            field=models.CharField(blank=True, help_text='ElevenLabs Voice ID', max_length=100, null=True),
        ),
    ]
