# Generated by Django 5.2.1 on 2025-05-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_influencer_voiceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='model_id',
            field=models.CharField(blank=True, help_text='OpenAI Model ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='System Prompt', null=True),
        ),
    ]
