# Generated by Django 5.2.1 on 2025-06-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_influencer_model_id_influencer_system_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='model_id',
            new_name='response_model_id',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='system_prompt',
            new_name='response_system_prompt',
        ),
        migrations.AddField(
            model_name='influencer',
            name='speech_style_model_id',
            field=models.CharField(blank=True, help_text='OpenAI Model ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='speech_style_system_prompt',
            field=models.TextField(blank=True, help_text='System Prompt', null=True),
        ),
    ]
