# Generated by Django 5.2.1 on 2025-06-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_influencer_model_id_influencer_system_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='system_prompt',
            new_name='feature_system_prompt',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='model_id',
        ),
        migrations.AddField(
            model_name='influencer',
            name='feature_model_id',
            field=models.CharField(blank=True, help_text='Apply Featrue OpenAI Model ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='speech_model_id',
            field=models.CharField(blank=True, help_text='Reflect Speech OpenAI Model ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='speech_system_prompt',
            field=models.CharField(blank=True, help_text='Relfect Speech System Prompt', null=True),
        ),
    ]
