# Generated by Django 5.2.1 on 2025-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_rename_system_prompt_influencer_feature_system_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='speech_system_prompt',
            field=models.TextField(blank=True, help_text='Relfect Speech System Prompt', null=True),
        ),
    ]
