# Generated by Django 5.2.1 on 2025-06-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0005_alter_influencer_speech_system_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer_auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('total_chat_received', models.IntegerField(default=0)),
                ('thumbs_up', models.IntegerField(default=0)),
                ('price_per_chat', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='influencers/')),
            ],
        ),
    ]
