# Generated by Django 5.2.1 on 2025-06-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_influencer_auto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Influencer_auto',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='price_per_chat',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='thumbs_up',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='total_chat_received',
        ),
        migrations.AddField(
            model_name='influencer',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='feature_model_id',
            field=models.CharField(blank=True, help_text='Apply Feature OpenAI Model ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='speech_system_prompt',
            field=models.TextField(blank=True, help_text='Reflect Speech System Prompt', null=True),
        ),
    ]
