# Generated by Django 5.2.1 on 2025-06-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0007_delete_influencer_auto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='created_mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
    ]
