# Generated by Django 5.2.1 on 2025-06-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0008_influencer_created_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='created_mode',
            field=models.CharField(choices=[('finetune', 'Finetune'), ('non-finetune', 'Non-Finetune')], default='non-finetune', max_length=15),
        ),
    ]
