# Generated by Django 5.2.1 on 2025-06-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0009_alter_influencer_created_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='influencers.influencer')),
            ],
        ),
    ]
